# Generated by Django 3.2.9 on 2021-12-02 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('idMovie', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('publicationDate', models.DateField(blank=True, null=True)),
                ('originalLanguage', models.CharField(blank=True, max_length=45, null=True)),
                ('genre', models.CharField(blank=True, max_length=45, null=True)),
                ('director', models.CharField(blank=True, max_length=45, null=True)),
                ('screenwriter', models.CharField(blank=True, max_length=45, null=True)),
                ('countryOfOrigin', models.CharField(blank=True, max_length=45, null=True)),
                ('producer', models.CharField(blank=True, max_length=45, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('idSeries', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('publicationDate', models.DateField(blank=True, null=True)),
                ('seasonCount', models.IntegerField(blank=True, null=True)),
                ('totalEpisodeCount', models.IntegerField(blank=True, null=True)),
                ('originalLanguage', models.CharField(blank=True, max_length=45, null=True)),
                ('countryOfOrigin', models.CharField(blank=True, max_length=45, null=True)),
                ('genre', models.CharField(blank=True, max_length=45, null=True)),
                ('broadcaster', models.CharField(blank=True, max_length=45, null=True)),
                ('spinoff', models.IntegerField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('producer', models.CharField(blank=True, max_length=45, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitles', models.TextField()),
                ('idMovie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.movie')),
                ('idSeries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.series')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeData',
            fields=[
                ('idEpisode', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('seasonNumber', models.IntegerField()),
                ('episodeNumber', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('idSeries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.series')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('dateOfBirth', models.DateField()),
                ('login', models.CharField(max_length=45)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duePayment', models.FloatField()),
                ('borrowedDate', models.DateField()),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.client')),
                ('idSeries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.series')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duePayment', models.FloatField()),
                ('borrowedDate', models.DateField()),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.client')),
                ('idMovie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.movie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
