# Generated by Django 3.2.9 on 2021-11-03 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('idMovie', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('publicationDate', models.DateField()),
                ('originalLanguage', models.CharField(max_length=45)),
                ('genre', models.CharField(max_length=45)),
                ('director', models.CharField(max_length=45)),
                ('screenwriter', models.CharField(max_length=45)),
                ('countryOfOrigin', models.CharField(max_length=45)),
                ('producer', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('idSeries', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('publicationDate', models.DateField()),
                ('seasonCount', models.IntegerField()),
                ('totalEpisodeCount', models.IntegerField()),
                ('originalLanguage', models.CharField(max_length=45)),
                ('countryOfOrigin', models.CharField(max_length=45)),
                ('genre', models.CharField(max_length=45)),
                ('broadcaster', models.CharField(max_length=45)),
                ('spinoff', models.IntegerField()),
                ('startDate', models.DateField()),
                ('producer', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('dateOfBirth', models.DateField()),
                ('login', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('accessLevel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subtitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitles', models.TextField()),
                ('idMovie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.movie')),
                ('idSeries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.series')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeData',
            fields=[
                ('idEpisode', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('seasonNumber', models.IntegerField()),
                ('episodeNumber', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('idSeries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.series')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duePayment', models.FloatField()),
                ('borrowedDate', models.DateField()),
                ('idSeries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.series')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.user')),
            ],
        ),
    ]
