# Generated by Django 3.2.9 on 2021-11-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WypozyczApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedmovies',
            name='idSeries',
        ),
        migrations.AddField(
            model_name='borrowedmovies',
            name='idMovie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.movie'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BorrowedSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duePayment', models.FloatField()),
                ('borrowedDate', models.DateField()),
                ('idSeries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.series')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WypozyczApp.user')),
            ],
        ),
    ]
