# Generated by Django 3.2.9 on 2021-11-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WypozyczApp', '0004_auto_20211130_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='idMovie',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='idSeries',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='idUser',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
